name: flutter_practice
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^3.0.1
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf
          weight: 900
